version: '3.7'
services:
  bddevolucion:
    container_name: bddevolucion
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: bddevolucion
      MYSQL_DATABASE: bddevolucion
    ports:
      - '3306:3306'
    volumes:
      - ./Devolucion/bddevolucion:/var/lib/mysql
  appdevolucion:
    container_name: appdevolucion
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8001:80'
    expose:
      - '8001'
    volumes:
      - ./Devolucion/app:/var/www/html
    depends_on:
      - bddevolucion
  bdprestamos:
    container_name: bdprestamos
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: bdprestamos
      MYSQL_DATABASE: bdprestamos
    ports:
      - '3307:3306'
    volumes:
      - ./Prestamos/bdprestamos:/var/lib/mysql
  appprestamos:
    container_name: appprestamos
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8002:80'
    expose:
      - '8002'
    volumes:
      - ./Prestamos/app:/var/www/html
    depends_on:
      - bdprestamos
  bdgateway:
    container_name: bdgateway
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: bdgateway
      MYSQL_DATABASE: bdgateway
    ports:
      - '3308:3306'
    volumes:
      - ./ApiGateway/bdGateway:/var/lib/mysql
  appgateway:
    container_name: appgateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8003:80'
    expose:
      - '8003'
    volumes:
      - ./ApiGateway/App:/var/www
      - ./ApiGateway/App/public:/var/www/html
    depends_on:
      - bdgateway
  appcliente:
    container_name: appcliente
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8004:80'
    volumes:
      - ./AppCliente/App:/var/www
      - ./AppCliente/App/public:/var/www/html
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CREATE_TOPICS: "pretamos:1:1"







